language: node_js
node_js: "-9.4.0"
before_install:
- openssl aes-256-cbc -K $encrypted_f4b75d109fc1_key -iv $encrypted_f4b75d109fc1_iv
  -in id_rsa.enc -out travis/id_rsa -d
 - chmod 600 ~/.ssh/id_rsa 
 - echo -e "Host 111.230.239.56\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: "- npm run test"
install: "- npm install"
